language: python
language: python
sudo: required
dist: xenial
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "nightly"
script:
  - pip install -r requirements-dev.txt
  - ./test.sh python
git:
  depth: false