#!/bin/sh
ICDIFF_OPTIONS=$(git config --get icdiff.options)
GITPAGER=$(git config --get icdiff.pager)

if [ -z "$GITPAGER" ]; then
  GITPAGER=$(git config --get --default "${PAGER:-less}" core.pager)
fi

if [ "$GITPAGER" = "more" ] || [ "$GITPAGER" = "less" ]; then
  GITPAGER="$GITPAGER -R"
fi

git difftool --no-prompt --extcmd="icdiff $ICDIFF_OPTIONS" "$@" | $GITPAGER
