#!/bin/sh
GITPAGER=$(git config --get core.pager)

if [ -z "$GITPAGER" ]; then
  GITPAGER="$PAGER"
fi

if [ -z "$GITPAGER" ]; then
  GITPAGER="less"
fi

if [ "$GITPAGER" = "more" -o "$GITPAGER" = "less" ]; then
  GITPAGER="$GITPAGER -R"
fi

git difftool --no-prompt --extcmd icdiff "$@" | $GITPAGER
